FROM node:24-alpine

WORKDIR /app

ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1

COPY package*.json ./
RUN npm ci

COPY prisma/schema.prisma ./prisma/schema.prisma
RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "dev:fast", "--", "--hostname", "0.0.0.0"]
